name: Compile Sketch

on:
  - push
  - pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/arduino-lint-action@v2
        with:
          library-manager: update
          compliance: strict
          fqbn: arduino:avr:uno
          sketch-paths: |
            - "TinyDX FIRMWARE/TinyDX_V1.4"

  compile-sketch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # See: https://github.com/arduino/compile-sketches#readme
      - name: Compile sketches
        uses: arduino/compile-sketches@v1
        with:
          fqbn: arduino:avr:uno
          sketch-paths: |
            - "TinyDX FIRMWARE/TinyDX_V1.4"
          libraries: |
            - name: Etherkit Si5351
